[package]
name = "physics_informed_anomaly_detection_in_a_wind_turbine_using_python_with_an_autoencoder_transformer_rs"
description = "Python bindings (PyO3) for physics_informed_anomaly_detection_in_a_wind_turbine_using_python_with_an_autoencoder_transformer_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "physics_informed_anomaly_detection_in_a_wind_turbine_using_python_with_an_autoencoder_transformer_rs"
crate-type = ["cdylib"]

[dependencies]
physics_informed_anomaly_detection_in_a_wind_turbine_using_python_with_an_autoencoder_transformer_core = { path = "../core" }
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
